### ISSUE TITLE
Error while executing 

### ISSUE THREAD

**Issue by wordblind** [groupgets/pylepton#36]
pi@raspberrypi:~/pylepton $ sudo pylepton_overlay -a 255
`Traceback (most recent call last):
  File "/usr/local/bin/pylepton_overlay", line 29, in main
    with Lepton(device) as l:
  File "/usr/local/lib/python2.7/dist-packages/pylepton/Lepton.py", line 84, in __enter__
    ioctl(self.__handle, SPI_IOC_RD_MODE, struct.pack("=B", Lepton.MODE))
IOError: [Errno 25] Inappropriate ioctl for device
`

**Comment by Rellim7** [comment]
@wordblind did you ever solve this issue?  I am experiencing the same

**Comment by alexpp97** [comment]
i have the same problem
